# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYVvl5AY3bajmunKJ3EkEytaVEqSXoAr
"""

!pip install pgmpy

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.inference import VariableElimination
import pandas as pd

# Data
data = pd.DataFrame({
    'Rain': ['No','No','Yes','Yes','No','Yes','Yes','No'],
    'TrafficJam': ['Yes','No','Yes','No','Yes','Yes','No','No'],
    'ArriveLate': ['Yes','No','Yes','No','No','Yes','Yes','No']
})

# Model
model = DiscreteBayesianNetwork([
    ('Rain', 'TrafficJam'),
    ('TrafficJam', 'ArriveLate')
])

# Train model
model.fit(data)

# Inference
infer = VariableElimination(model)
result = infer.query(variables=['ArriveLate'], evidence={'Rain': 'Yes'})

print(result)