# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rk1GOZ5MZoI8PT5wkqsi5gNFI-31_y0g
"""

!pip install pgmpy

from pgmpy.models import DiscreteBayesianNetwork

import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination

# Dataset
data = pd.DataFrame({
    'Study': ['High','Low','High','Low','High','Low','High','Low'],
    'Sleep': ['Good','Poor','Good','Poor','Good','Poor','Good','Poor'],
    'Pass':  ['Yes','No','Yes','No','Yes','No','Yes','No']
})

# Model
model = DiscreteBayesianNetwork([
    ('Study','Pass'),
    ('Sleep','Pass')
])

# Train
model.fit(data, estimator=MaximumLikelihoodEstimator)

# Inference
infer = VariableElimination(model)

# Query
result = infer.query(variables=['Pass'], evidence={'Study':'High'})
print(result)